### ISSUE TITLE
Confusion with export and export default in JavaScript

### ISSUE THREAD

**Issue by danbillingham** [HandlebarLabs/code-and-coffee#12]
So I have this code below and it pulls in the various linked files fine. But It only works if I run one of the exports - for example if I hide FadeToView - greetings works and i i hide Greetings fade to view works, but not when they are both on the same page.

## How can I get started?

```javascript
import React, { Component } from 'react';
import { AppRegistry, Text, View } from 'react-native';

import FadeInView from './components/FadeInView';
import Greeting from './Greeting';

export default class App extends React.Component {
  render() {
    return (
      <View
        style={{
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <FadeInView
          style={{
            width: 250,
            height: 50,
            backgroundColor: 'red',
          }}
        >
          <Text
            style={{
              fontSize: 28,
              textAlign: 'center',
              margin: 10,
            }}
          >
            {' '}
            Fading in{' '}
          </Text>{' '}
        </FadeInView>{' '}
      </View>
    );
  }
}

export default class LotsOfGreetings extends Component {
  render() {
    return (
      <View
        style={{
          alignItems: 'center',
        }}
      >
        <Greeting name="Rexxar" />
        <Greeting name="Jaina" />
        <Greeting name="Valeera" />
      </View>
    );
  }
}

AppRegistry.registerComponent('App', () => App);

```

Thanks for inviting me in - I hope you won't regret it.

**Comment by spencercarli** [comment]
I think the issue you're seeing is caused by having `export default` twice (you can only have that once per file. In this case, it's not necessary at all because you call `AppRegistery` in this file.

Try replacing
`export default class App extends React.Component` with `class App extends React.Component` and `export default class LotsOfGreetings extends Component` with `class LotsOfGreetings extends Component`.

[Here's a nice cheat sheet](https://hackernoon.com/import-export-default-require-commandjs-javascript-nodejs-es6-vs-cheatsheet-different-tutorial-example-5a321738b50f) for import/export/export default in JavaScript.

Let me know if this successfully answers your question!

**Comment by danbillingham** [comment]
Thank you!

A big issue I am having is finding tutorials that go back to basics - right back to stage one - they all assume some level - but I don’t quit easy. 

Thanks again. 


Dan Billingham
Creative

Floe AB
+ 46 (0)70 - 239 77 14

**Comment by spencercarli** [comment]
Here's a [bunch of articles](https://github.com/wesbos/es6-articles) on the subject that may help. I suggest picking up one thing at a time - it's overwhelming otherwise 😄
