### ISSUE TITLE
Lag when looping audio

### ISSUE THREAD

**Issue by desaetiis** [HandlebarLabs/code-and-coffee#13]
## Question Description

Hey Spencer,

I've been working on a hybrid audio app in react native - first attempt at react native - that requires a relatively short audio clip to loop seamlessly. I can't seem to make that happen. Even though the clip is perfectly edited so it loops perfectly, it will not. I am requesting the file from the assets/audio directory on my hard drive. The file is an mp3. Oh and I am using the expo/playlist example https://github.com/expo/playlist-example as a starting point. I will mention that I've rebuilt the app in swift, xcode and used the same audio files and they loop perfectly. Am I correct in assuming that react-native can't handle audio with this level of precision?

## How can I get started?

A few examples of what to provide:
- Do you have a code sample I can use?
https://github.com/expo/playlist-example Try to replace audio here and set it to loop (-1)
- Github repo I can download? What should I look for?
- Docs/getting started resources I should look at?

Thank you, thank you.

Felix

**Comment by spencercarli** [comment]
Interesting. I've never worked with looping audio in React Native but I'm curious if this an Expo specific issue. Have you tried this with something like [`react-native-sound`](https://github.com/zmxv/react-native-sound) outside of an Expo app?

There might be an issue/delay due to the async nature of Expo sounds and the way things interact with the bridge, but i'm really not sure.

**Comment by spencercarli** [comment]
Gonna go ahead and close this.
