### ISSUE TITLE
React Native and Facebook

### ISSUE THREAD

**Issue by ghost** [HandlebarLabs/code-and-coffee#16]
I've to integrate a React Native app (into Expo) with Facebook, the user can choose one image from your device gallery and share it to Facebook feed (i've to catch callback of operation success too), i’ve
Googled for ours and i’ve surprise this featured in not into React Core (is Facebook too).
I’ve try "Share" React Native function but on Android you can’t share local image (i've to upload it to remote server and the share the remote url), "react-native-fbsdk" (or other modules with link command) require exit from Expo... there are other ways?
Thanks

**Comment by spencercarli** [comment]
A few thoughts...

> surprise this featured in not into React Core

This isn't a requirement of the framework, it's an application feature. Therefore it should be up to the app to integrate, thus no need to add bloat to the framework.

> "react-native-fbsdk" (or other modules with link command) require exit from Expo... there are other ways?

Expo has integrated a Facebook SDK https://docs.expo.io/versions/v25.0.0/sdk/facebook.html#content

> I’ve try "Share" React Native function but on Android you can’t share local image

This makes sense. I don't see how it would work any other way. Facebook needs a URL to fetch the image from.

I hope that helps somewhat. I'm going to close this since it doesn't follow the template for new issues.
